FROM ruby:3.3-bookworm

RUN apt-get update -qq && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

EXPOSE 3000

CMD ["bash", "-c", "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"]
